### ISSUE TITLE
Linked list using c

### ISSUE THREAD

**Issue by anjisnu07** [akashrchandran/college-labs#6]
Create a singly linked list and add this operations.
1.insert from end
2.insert from starting
3.insert at a certain position
4.display linked list element
5.delete element from end
6.delete element from front
7.delete element from a certain position.
.......So on I can add double and circular too.
Assign me for this

**Comment by akashrchandran** [comment]
I have assigned it to you. For now just create a folder and put the file in that. I will organise it later.👍
